#!/bin/zsh

# printf '%s' "Are you in the right folder? [y]/[n]: "
# read ans
# printf '\n'

# if [ $ans = "n" ]
#    printf '%s' "Which folder should you be in? -> "
#    read folder
#    cd $folder
# fi

# printf '\n'

git add README.md

printf '%s' "Commit message: "
read message
printf '\n'

git commit -m "$message"
git push -u origin main

printf '%s\n' "Done!"