#!/bin/zsh

current_folder=$(basename $PWD)

printf '%s' "commit message: "
read argument

#echo "$current_folder and $argument"

printf '%s' "pushing changes.."

git add .
git commit -m "$argument"
git push -u origin main

printf '%s' "pulling changes into ~/.vscode/extensions/$current_folder/"

cd ~/.vscode/extensions/$current_folder
git pull
